const TransactionFormActionTypes = {
	UPDATE_TRANSACTIONFORM_AMOUNT: "UPDATE_TRANSACTIONFORM_AMOUNT",
	UPDATE_TRANSACTIONFORM_TYPE: "UPDATE_TRANSACTIONFORM_TYPE",
	UPDATE_TRANSACTIONFORM_CATEGORY: "UPDATE_TRANSACTIONFORM_CATEGORY"
};

export default TransactionFormActionTypes;
